[workspace]
members = [
    "codegen",
    "core",
    "core/net",
    "core/text",
    "core/pos",
    "core/buf",
    "core/fs",

    "server",
    "server/net",
    "server/player",
    "server/types",
    "server/jaggrab"
]