[package]
name = "mithril-codegen"
version = "0.1.0"
authors = ["Connor Spencer Harries <connor@harmony-labs.org.uk>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits", "derive"] }
quote = "1.0"
proc-macro2 = "1.0"
once_cell = "1"