[package]
name = "mithril-core"
version = "0.1.0"
authors = ["Connor Spencer Harries <connor@harmony-labs.org.uk>"]
edition = "2018"

[features]
test-equality = ["mithril-net/test-equality"]

[dependencies]
mithril-net = { path = "net" }
mithril-pos = { path = "pos" }
mithril-fs = { path = "fs" }
